feat: support fzf-lua as a folder picker
pimalaya/himalaya-vim pull request #17
Opened 2024-12-21 22:26 UTC by parisni

fzf-lua is the default picker in lazyvim distro.

fixes #15

2024-12-24 02:19 UTC, soywod requested changes
Thanks a lot for your contribution, much appreciated :pray: I just had a minor change request on the changelog, otherwise we can merge!

2024-12-24 02:19 UTC, soywod commented on CHANGELOG.md
> +### Added
Duplicate section

2024-12-26 22:20 UTC, parisni commented on CHANGELOG.md
> +### Added
fixed

2024-12-31 16:02 UTC, soywod approved these changes

2024-12-31 16:02 UTC, merged

2024-12-31 16:03 UTC, soywod commented
Thank you, sorry for the delay!